### PR TITLE
Copy pids

### PR DESCRIPTION
**Pull request by sax**
This change allows overrides for one pid to be copied onto another pid.

I also ran `mix format` on the entire project.

### CODE REVIEW

**Comment by sax** [comment]
@hdtafur @aarongraham would you mind taking a look at this, and potentially merging and releasing a new version?

FYI this makes it so you can write a plug (added only in the `test` env, for Wallaby), that copies all overrides from the test pid onto the server pid. Then no other code in the project needs to know about the gestalt pid.

**Review by sparta-developers — APPROVED** [review]
Looks good to us bro! 🚢 💪

**Comment by sax** [comment]
FYI I no longer have write access to the repo.

**Comment by gregwoodward** [comment]
Sax, you should have write access again. I had removed you from the sparta dev team group, but I forgot about this repo.

**Pull request merged**
